import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from "../components/header/header";
import Main from "../components/main/main";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='flex w-full h-screen'>
        <Header />
        <Main />
      </div>
    </div>
  )
}
